#!/bin/bash

# Arch Install Script by Liam
set -e

echo "=== Arch Linux Automated Install Script ==="
echo "Ensure you are in UEFI mode."

# Verify UEFI
if [[ $(cat /sys/firmware/efi/fw_platform_size) -ne 64 ]]; then
    echo "Error: System is not in UEFI mode. Exiting."
    exit 1
fi

# Internet Setup
echo "=== Setting up Internet ==="
ip link
echo "Enter your Wi-Fi network name (leave blank for Ethernet):"
read WIFI_NAME

if [[ -n "$WIFI_NAME" ]]; then
    iwctl
    echo "Inside iwctl, type:"
    echo "station wlan0 get-networks"
    echo "station wlan0 connect \"$WIFI_NAME\""
    echo "Then type 'exit' to continue."
    iwctl
fi

# Partitioning
echo "=== Disk Partitioning ==="
lsblk
echo "Enter the disk you want to partition (e.g., nvme0n1, sda):"
read DISK
cfdisk /dev/$DISK

# Ask for partitions
echo "Enter the EFI partition (e.g., ${DISK}p1 or sda1):"
read EFI_PART
echo "Enter the root partition (e.g., ${DISK}p2 or sda2):"
read ROOT_PART

# Format partitions
echo "=== Formatting Partitions ==="
mkfs.ext4 /dev/$ROOT_PART
mount /dev/$ROOT_PART /mnt
mkdir -p /mnt/boot/efi

echo "Format EFI partition? (yes/no)"
read FORMAT_EFI
if [[ "$FORMAT_EFI" == "yes" ]]; then
    mkfs.fat -F 32 /dev/$EFI_PART
fi

mount /dev/$EFI_PART /mnt/boot/efi

# Configure Mirrorlist
echo "=== Configuring Mirrorlist ==="
reflector --country Australia --latest 5 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist

# Install Base System
echo "=== Installing Base System ==="
pacstrap -K /mnt base grub efibootmgr linux linux-firmware sudo nano neovim firefox gnome networkmanager

# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into Installed System
arch-chroot /mnt /bin/bash <<EOF

echo "=== Setting Timezone ==="
ln -sf /usr/share/zoneinfo/Australia/Sydney /etc/localtime
hwclock --systohc

echo "=== Configuring Locale ==="
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

echo "=== Setting Hostname ==="
echo "Enter a hostname for your system:"
read HOSTNAME
echo "\$HOSTNAME" > /etc/hostname

echo "=== Setting Root Password ==="
passwd

echo "=== Creating User ==="
echo "Enter a username:"
read USERNAME
useradd -m -G wheel \$USERNAME
passwd \$USERNAME
sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

echo "=== Configuring Bootloader ==="
mkinitcpio -P
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --modules="tpm" --disable-shim-lock
grub-mkconfig -o /boot/grub/grub.cfg

EOF

# Unmount and Finish
echo "=== Finishing Installation ==="
umount -R /mnt
echo "Remove installation media and type 'reboot' to finish."
